/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodhub;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 18010
 */
public class AddItemsPage extends javax.swing.JFrame {

    /**
     * Creates new form AddItemsPage
     */
    public String Iteam;
    public Connection connection;
    public AddItemsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        productInfoBrandName = new javax.swing.JLabel();
        productInfoBrandName7 = new javax.swing.JLabel();
        productInfoBrandName5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        UploadImage = new javax.swing.JButton();
        FItem = new javax.swing.JTextField();
        FID = new javax.swing.JTextField();
        FPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 750));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Items");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 77, 64));
        jLabel11.setText("Food Item:");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 77, 64));
        jLabel15.setText(" Price:");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 77, 64));
        jLabel12.setText("Food ID:");

        productInfoBrandName.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        productInfoBrandName.setForeground(new java.awt.Color(0, 77, 64));

        productInfoBrandName7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        productInfoBrandName7.setForeground(new java.awt.Color(0, 77, 64));

        productInfoBrandName5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        productInfoBrandName5.setForeground(new java.awt.Color(0, 77, 64));

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Image Uploader");

        jButton1.setBackground(new java.awt.Color(0, 121, 107));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jButton1.setText("Add Item");
        jButton1.setActionCommand("AddItem");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 77, 64));
        jLabel13.setText("Select Category");

        jComboBox1.setBackground(new java.awt.Color(0, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biriyani Items", "Kabab Items", "Italian  Items", "Mexican items", "Indian Items", "Chinese Items" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        UploadImage.setBackground(new java.awt.Color(0, 121, 107));
        UploadImage.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        UploadImage.setText("Upload");
        UploadImage.setActionCommand("AddItem");
        UploadImage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        UploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(FID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FItem, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(productInfoBrandName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productInfoBrandName7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productInfoBrandName5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productInfoBrandName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(productInfoBrandName7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productInfoBrandName5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UploadImage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ownerLoginPage o = new ownerLoginPage();
        String ID="180104001";
        String Rname = null;
        String id=FID.getText();
        String iteam=FItem.getText();
        String price=FPrice.getText();
        
        
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Restaurant_Name FROM Restaurant WHERE Restaurant_ID='"+ID+"'");
            if (rs.next()) 
            {
               Rname=rs.getString(1);
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        String value=(String)jComboBox1.getSelectedItem();
        if (value.equalsIgnoreCase("Biriyani Items"))
        {
            String Oil_level="8.0" ;
        String Spice_Level="7.0" ;
        String Masala_rating="9.0"  ;
        String Taste_rating="7.5"  ;
        String Avg_rating="7.0"  ;
        String photo="kacchi.jpg"  ;
            
            
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (Rname.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Restaurant Name");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Biriyani_Items  VALUES ('"+id+"','"+iteam+"','"+Rname+"','"+price+"','"+Oil_level+"','"+Spice_Level+"','"+Masala_rating+"','"+Taste_rating+"','"+Avg_rating+"','"+photo+"','"+ID+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added");   
                
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else if(value.equalsIgnoreCase("Chinese Items"))
        {
            
        String Spice_Level="7.0" ;
        String Sauce_rating="9.0"  ;
        String Taste_rating="7.5"  ;
        String Avg_rating="7.0"  ;
        String photo="FriedRice.jpg"  ;
            
            
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (Rname.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Restaurant Name");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Chinese_Foods  VALUES ('"+id+"','"+iteam+"','"+Rname+"','"+price+"','"+Spice_Level+"','"+Sauce_rating+"','"+Taste_rating+"','"+Avg_rating+"','"+photo+"','"+ID+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added");   
                
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        else if(value.equalsIgnoreCase("Kabab Items"))
        {
            
        String oil_Level="7.0" ;
        String Masala_rating="9.0"  ;
        String Sauce_rating="9.0"  ;
        String Taste_rating="7.5"  ;
        String Avg_rating="7.0"  ;
        String photo="Shik.jpg"  ;
            
            
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (Rname.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Restaurant Name");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Kabab_Items  VALUES ('"+id+"','"+iteam+"','"+Rname+"','"+price+"','"+oil_Level+"','"+Masala_rating+"','"+Sauce_rating+"','"+Taste_rating+"','"+Avg_rating+"','"+photo+"','"+ID+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added");   
                
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        else if(value.equalsIgnoreCase("Italian  Items"))
        {
            
        String Cheese_Level="7.0" ;
        String Taste_rating="7.5"  ;
        String Avg_rating="7.0"  ;
        String photo="Pizza.jpg"  ;
            
            
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (Rname.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Restaurant Name");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Italian_Foods  VALUES ('"+id+"','"+iteam+"','"+Rname+"','"+price+"','"+Cheese_Level+"','"+Taste_rating+"','"+Avg_rating+"','"+photo+"','"+ID+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added");   
                
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        else if(value.equalsIgnoreCase("Mexican items"))
        {
            
        
        String M_rating="9.0"  ;
        String Taste_rating="7.5"  ;
        String Avg_rating="7.0"  ;
        String photo="Subway.jpg"  ;
            
            
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (Rname.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Restaurant Name");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Mexican_Foods  VALUES ('"+id+"','"+iteam+"','"+Rname+"','"+price+"','"+M_rating+"','"+Taste_rating+"','"+Avg_rating+"','"+photo+"','"+ID+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added");   
                
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        else if(value.equalsIgnoreCase("Indian Items"))
        {
            
        String Spice_Level="7.0" ;
        String M_rating="9.0"  ;
        String Taste_rating="7.5"  ;
        String Avg_rating="7.0"  ;
        String photo="Dosa.jpg"  ;
            
            
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (Rname.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Restaurant Name");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO Indian_Foods  VALUES ('"+id+"','"+iteam+"','"+Rname+"','"+price+"','"+Spice_Level+"','"+M_rating+"','"+Taste_rating+"','"+Avg_rating+"','"+photo+"','"+ID+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Item Added");   
                
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UploadImageActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItemsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItemsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FID;
    private javax.swing.JTextField FItem;
    private javax.swing.JTextField FPrice;
    private javax.swing.JButton UploadImage;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel productInfoBrandName;
    public javax.swing.JLabel productInfoBrandName5;
    public javax.swing.JLabel productInfoBrandName7;
    // End of variables declaration//GEN-END:variables
}
