/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodhub;

/**
 *
 * @author 18010
 */
public class firstPage extends javax.swing.JFrame {

    /**
     * Creates new form firstPage
     */
    public firstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mLabel = new java.awt.Label();
        toUserLoginPage = new javax.swing.JLabel();
        toOwnerLoginPage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mLabel.setAlignment(java.awt.Label.CENTER);
        mLabel.setBackground(new java.awt.Color(0, 153, 153));
        mLabel.setFont(new java.awt.Font("Berlin Sans FB", 0, 48)); // NOI18N
        mLabel.setForeground(new java.awt.Color(255, 255, 255));
        mLabel.setText("Welcome to foodHUB");
        getContentPane().add(mLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 490, 168));

        toUserLoginPage.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        toUserLoginPage.setForeground(new java.awt.Color(0, 153, 153));
        toUserLoginPage.setText("Login as a USER");
        toUserLoginPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toUserLoginPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toUserLoginPageMouseClicked(evt);
            }
        });
        getContentPane().add(toUserLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        toOwnerLoginPage.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        toOwnerLoginPage.setForeground(new java.awt.Color(0, 153, 153));
        toOwnerLoginPage.setText("Login as a Restaurant Owner");
        toOwnerLoginPage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toOwnerLoginPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toOwnerLoginPageMouseClicked(evt);
            }
        });
        getContentPane().add(toOwnerLoginPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 590, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restaurant .png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hmainBG.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toUserLoginPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toUserLoginPageMouseClicked
        // TODO add your handling code here:
        dispose();
        userLogin userLogin= new userLogin();
        userLogin.show();
    }//GEN-LAST:event_toUserLoginPageMouseClicked

    private void toOwnerLoginPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toOwnerLoginPageMouseClicked
        // TODO add your handling code here:
        dispose();
        ownerLoginPage ownerLogin= new ownerLoginPage();
        ownerLogin.show();
    }//GEN-LAST:event_toOwnerLoginPageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private java.awt.Label mLabel;
    private javax.swing.JLabel toOwnerLoginPage;
    private javax.swing.JLabel toUserLoginPage;
    // End of variables declaration//GEN-END:variables
}
