/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodhub;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.jar.Attributes.Name;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 180104081
 */
public class registrationUserPage extends javax.swing.JFrame {

    /**
     * Creates new form registrationUserPage
     */
    public registrationUserPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        regUserName = new javax.swing.JTextField();
        regName = new javax.swing.JTextField();
        regMail = new javax.swing.JTextField();
        regPass = new javax.swing.JPasswordField();
        reTypePass = new javax.swing.JPasswordField();
        RegisterToLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NAME :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("USER NAME :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EMAIL ID :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PASSWORD :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RE_TYPE PASSWORD : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        regUserName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        regUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(regUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, -1));

        regName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jPanel1.add(regName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 260, -1));

        regMail.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        regMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMailActionPerformed(evt);
            }
        });
        jPanel1.add(regMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 260, 30));

        regPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPassActionPerformed(evt);
            }
        });
        jPanel1.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 260, -1));

        reTypePass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(reTypePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 240, -1));

        RegisterToLogin.setBackground(new java.awt.Color(0, 255, 255));
        RegisterToLogin.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        RegisterToLogin.setForeground(new java.awt.Color(0, 0, 139));
        RegisterToLogin.setText("Registration");
        RegisterToLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RegisterToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterToLoginActionPerformed(evt);
            }
        });
        jPanel1.add(RegisterToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registerUser.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public Connection connection;
    
    private void regMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regMailActionPerformed

    private void regUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUserNameActionPerformed

    private void regPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPassActionPerformed

    private void RegisterToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterToLoginActionPerformed
        // TODO add your handling code here:
        String fullName=regName.getText();
        String userName=regUserName.getText();
        String email=regMail.getText();
        String password=regPass.getText();
        String confirmPass=reTypePass.getText();
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
                
            if (email.equals("")) {
            JOptionPane.showMessageDialog(this, "Type Email");              
            }
            else
            {
                
                Statement statement = connection.createStatement();
                String sql="INSERT INTO General_User VALUES ('"+fullName+"','"+userName+"','"+email+"','"+password+"','"+confirmPass+"')";
                
                PreparedStatement prepare=connection.prepareStatement(sql);
                prepare.executeUpdate();
                JOptionPane.showMessageDialog(this, "Registration Complete.");   
                dispose();
                userLogin home= new userLogin();
                home.show();
            }  
            connection.close();
        }catch(SQLException ex){
             Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(registrationUserPage.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_RegisterToLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationUserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationUserPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterToLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField reTypePass;
    private javax.swing.JTextField regMail;
    private javax.swing.JTextField regName;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JTextField regUserName;
    // End of variables declaration//GEN-END:variables
}
