/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodhub;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import project.ElectronicsDB;
import project.ProductInformation;
import project.ProductList;
import project.Search;

/**
 *
 * @author 18010
 */
public class userViewPage extends javax.swing.JFrame {

    /**
     * Creates new form userViewPage
     */public Connection connection;
   
    public userViewPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        accountButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        BtnBiriyani = new javax.swing.JButton();
        BtnKabab = new javax.swing.JButton();
        BtnChinese = new javax.swing.JButton();
        BtnItalian = new javax.swing.JButton();
        BtnIndian = new javax.swing.JButton();
        BtnMexican = new javax.swing.JButton();
        cardParentPanel1 = new javax.swing.JPanel();
        BiriyaniPane = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Biriyanitable = new javax.swing.JTable();
        searchPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        KababPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        KababTable = new javax.swing.JTable();
        ChineseFoodPane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChineseTable = new javax.swing.JTable();
        ItalianPane = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        ItalianTable = new javax.swing.JTable();
        MexicanPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MexicanTable = new javax.swing.JTable();
        IndianPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        IndianTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 121, 107));
        jPanel12.setPreferredSize(new java.awt.Dimension(1199, 72));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Food HUB");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        searchBar.setBackground(new java.awt.Color(0, 150, 136));
        searchBar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        searchBar.setForeground(new java.awt.Color(255, 255, 255));
        searchBar.setBorder(null);
        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
        });
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(0, 121, 107));
        searchButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Search_31px.png"))); // NOI18N
        searchButton.setToolTipText("Search");
        searchButton.setBorderPainted(false);
        searchButton.setContentAreaFilled(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setOpaque(true);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchButtonMouseReleased(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search");

        accountButton.setBackground(new java.awt.Color(0, 150, 136));
        accountButton.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        accountButton.setForeground(new java.awt.Color(255, 255, 255));
        accountButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Person_48px.png"))); // NOI18N
        accountButton.setToolTipText("Account Info");
        accountButton.setBorderPainted(false);
        accountButton.setContentAreaFilled(false);
        accountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accountButton.setOpaque(true);
        accountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                accountButtonMouseReleased(evt);
            }
        });
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178)
                .addComponent(accountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        BackgroundPanel.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 60));

        jPanel13.setBackground(new java.awt.Color(0, 150, 136));

        BtnBiriyani.setBackground(new java.awt.Color(0, 150, 136));
        BtnBiriyani.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        BtnBiriyani.setForeground(new java.awt.Color(255, 255, 255));
        BtnBiriyani.setText("Biriyani Items");
        BtnBiriyani.setToolTipText("Check what's new!");
        BtnBiriyani.setBorderPainted(false);
        BtnBiriyani.setContentAreaFilled(false);
        BtnBiriyani.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBiriyani.setOpaque(true);
        BtnBiriyani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBiriyaniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBiriyaniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBiriyaniMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnBiriyaniMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnBiriyaniMouseReleased(evt);
            }
        });
        BtnBiriyani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBiriyaniActionPerformed(evt);
            }
        });

        BtnKabab.setBackground(new java.awt.Color(0, 150, 136));
        BtnKabab.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        BtnKabab.setForeground(new java.awt.Color(255, 255, 255));
        BtnKabab.setText("Kabab Items");
        BtnKabab.setToolTipText("TV, Fridge, Electronic Devices");
        BtnKabab.setBorderPainted(false);
        BtnKabab.setContentAreaFilled(false);
        BtnKabab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnKabab.setOpaque(true);
        BtnKabab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnKababMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnKababMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnKababMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnKababMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnKababMouseReleased(evt);
            }
        });
        BtnKabab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKababActionPerformed(evt);
            }
        });

        BtnChinese.setBackground(new java.awt.Color(0, 150, 136));
        BtnChinese.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        BtnChinese.setForeground(new java.awt.Color(255, 255, 255));
        BtnChinese.setText("Chinese Food");
        BtnChinese.setToolTipText("Latest mobiles available on store!");
        BtnChinese.setBorderPainted(false);
        BtnChinese.setContentAreaFilled(false);
        BtnChinese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnChinese.setOpaque(true);
        BtnChinese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnChineseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnChineseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnChineseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnChineseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnChineseMouseReleased(evt);
            }
        });
        BtnChinese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChineseActionPerformed(evt);
            }
        });

        BtnItalian.setBackground(new java.awt.Color(0, 150, 136));
        BtnItalian.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        BtnItalian.setForeground(new java.awt.Color(255, 255, 255));
        BtnItalian.setText("Italian Food");
        BtnItalian.setToolTipText("Toys, Teddys and much more!");
        BtnItalian.setBorderPainted(false);
        BtnItalian.setContentAreaFilled(false);
        BtnItalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnItalian.setOpaque(true);
        BtnItalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnItalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnItalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnItalianMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnItalianMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnItalianMouseReleased(evt);
            }
        });
        BtnItalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnItalianActionPerformed(evt);
            }
        });

        BtnIndian.setBackground(new java.awt.Color(0, 150, 136));
        BtnIndian.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        BtnIndian.setForeground(new java.awt.Color(255, 255, 255));
        BtnIndian.setText("Indian Food");
        BtnIndian.setToolTipText("Toys, Teddys and much more!");
        BtnIndian.setBorderPainted(false);
        BtnIndian.setContentAreaFilled(false);
        BtnIndian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnIndian.setOpaque(true);
        BtnIndian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIndianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnIndianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnIndianMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnIndianMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnIndianMouseReleased(evt);
            }
        });
        BtnIndian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIndianActionPerformed(evt);
            }
        });

        BtnMexican.setBackground(new java.awt.Color(0, 150, 136));
        BtnMexican.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        BtnMexican.setForeground(new java.awt.Color(255, 255, 255));
        BtnMexican.setText("Mexican Food");
        BtnMexican.setToolTipText("Toys, Teddys and much more!");
        BtnMexican.setBorderPainted(false);
        BtnMexican.setContentAreaFilled(false);
        BtnMexican.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMexican.setOpaque(true);
        BtnMexican.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMexicanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnMexicanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnMexicanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BtnMexicanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnMexicanMouseReleased(evt);
            }
        });
        BtnMexican.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMexicanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(BtnBiriyani)
                .addGap(18, 18, 18)
                .addComponent(BtnKabab, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(BtnChinese, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnItalian, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BtnMexican, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BtnIndian, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnKabab, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnChinese, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnItalian, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBiriyani, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIndian, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnMexican, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackgroundPanel.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1210, 50));

        cardParentPanel1.setLayout(new java.awt.CardLayout());

        Biriyanitable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Biriyanitable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food Name", "Restaurant Name", "Price", "Average Rating", "Photo", "Food ID"
            }
        ));
        Biriyanitable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BiriyanitableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(Biriyanitable);

        javax.swing.GroupLayout BiriyaniPaneLayout = new javax.swing.GroupLayout(BiriyaniPane);
        BiriyaniPane.setLayout(BiriyaniPaneLayout);
        BiriyaniPaneLayout.setHorizontalGroup(
            BiriyaniPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BiriyaniPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        BiriyaniPaneLayout.setVerticalGroup(
            BiriyaniPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(BiriyaniPane, "card5");

        SearchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(SearchTable);

        javax.swing.GroupLayout searchPanel1Layout = new javax.swing.GroupLayout(searchPanel1);
        searchPanel1.setLayout(searchPanel1Layout);
        searchPanel1Layout.setHorizontalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchPanel1Layout.setVerticalGroup(
            searchPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(searchPanel1, "card9");

        KababTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        KababTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food Name", "Restaurant Name", "Price", "Average Rating", "Photo", "Food ID"
            }
        ));
        KababTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KababTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(KababTable);

        javax.swing.GroupLayout KababPaneLayout = new javax.swing.GroupLayout(KababPane);
        KababPane.setLayout(KababPaneLayout);
        KababPaneLayout.setHorizontalGroup(
            KababPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KababPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        KababPaneLayout.setVerticalGroup(
            KababPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(KababPane, "card4");

        ChineseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food Name", "Restaurant Name", "Price", "Average Rating", "Photo", "Food ID"
            }
        ));
        ChineseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChineseTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ChineseTable);

        javax.swing.GroupLayout ChineseFoodPaneLayout = new javax.swing.GroupLayout(ChineseFoodPane);
        ChineseFoodPane.setLayout(ChineseFoodPaneLayout);
        ChineseFoodPaneLayout.setHorizontalGroup(
            ChineseFoodPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChineseFoodPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChineseFoodPaneLayout.setVerticalGroup(
            ChineseFoodPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(ChineseFoodPane, "card3");

        ItalianTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ItalianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Restaurant Name", "Price", "Average Rating", "Photo", "Food ID"
            }
        ));
        ItalianTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItalianTable.setSelectionBackground(new java.awt.Color(0, 150, 136));
        ItalianTable.getTableHeader().setReorderingAllowed(false);
        ItalianTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalianTableMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(ItalianTable);

        javax.swing.GroupLayout ItalianPaneLayout = new javax.swing.GroupLayout(ItalianPane);
        ItalianPane.setLayout(ItalianPaneLayout);
        ItalianPaneLayout.setHorizontalGroup(
            ItalianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        ItalianPaneLayout.setVerticalGroup(
            ItalianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(ItalianPane, "card2");

        MexicanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food Name", "Restaurant Name", "Price", "Average Rating", "Photo", "Food ID"
            }
        ));
        MexicanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexicanTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(MexicanTable);

        javax.swing.GroupLayout MexicanPaneLayout = new javax.swing.GroupLayout(MexicanPane);
        MexicanPane.setLayout(MexicanPaneLayout);
        MexicanPaneLayout.setHorizontalGroup(
            MexicanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MexicanPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        MexicanPaneLayout.setVerticalGroup(
            MexicanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(MexicanPane, "card2");

        IndianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food Name", "Restaurant Name", "Price", "Average Rating", "Photo", "Food ID"
            }
        ));
        IndianTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IndianTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(IndianTable);

        javax.swing.GroupLayout IndianPaneLayout = new javax.swing.GroupLayout(IndianPane);
        IndianPane.setLayout(IndianPaneLayout);
        IndianPaneLayout.setHorizontalGroup(
            IndianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndianPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1188, Short.MAX_VALUE)
                .addContainerGap())
        );
        IndianPaneLayout.setVerticalGroup(
            IndianPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        cardParentPanel1.add(IndianPane, "card2");

        BackgroundPanel.add(cardParentPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1200, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        // TODO add your handling code here:
        searchBar.setText("");
    }//GEN-LAST:event_searchBarMouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBarActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseClicked

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonMouseExited

    private void searchButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMousePressed
        // TODO add your handling code here:
        searchButton.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_searchButtonMousePressed

    private void searchButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseReleased
        // TODO add your handling code here:
        searchButton.setBackground(new Color(0, 121, 107));
    }//GEN-LAST:event_searchButtonMouseReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        //ProductInformation.categoryChooser = "mobiles"; 

    }//GEN-LAST:event_searchButtonActionPerformed

    private void BtnBiriyaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBiriyaniMouseClicked
        // TODO add your handling code here:
        cardParentPanel1.removeAll();
        cardParentPanel1.add(BiriyaniPane);
        cardParentPanel1.repaint();
        cardParentPanel1.revalidate();
    }//GEN-LAST:event_BtnBiriyaniMouseClicked

    private void BtnBiriyaniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBiriyaniMouseEntered
        // TODO add your handling code here:;
        BtnBiriyani.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_BtnBiriyaniMouseEntered

    private void BtnBiriyaniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBiriyaniMouseExited
        // TODO add your handling code here:
        BtnBiriyani.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnBiriyaniMouseExited

    private void BtnBiriyaniMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBiriyaniMousePressed
        // TODO add your handling code here:
        BtnBiriyani.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnBiriyaniMousePressed

    private void BtnBiriyaniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBiriyaniMouseReleased
        // TODO add your handling code here:
        BtnBiriyani.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnBiriyaniMouseReleased

    private void BtnBiriyaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBiriyaniActionPerformed
        // TODO add your handling code here:
        
        
        ArrayList<Biriyani_List> list = null;
         try {
             list = Biriyani_IteamsDB.TableGenerator();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(userViewPage.class.getName()).log(Level.SEVERE, null, ex);
         }
        Object rowData[] = new Object[6];
        
        DefaultTableModel model =  (DefaultTableModel) Biriyanitable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        Biriyanitable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        Biriyanitable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        Biriyanitable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        Biriyanitable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        Biriyanitable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        Biriyanitable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getFood_Item();
            rowData[1] = list.get(i).getRestaurant_Name();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getAvg_rating();
            String temp = list.get(i).getPhoto();
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/Biriyani/"+temp));
            Image resizedImage = ii.getImage();
            ii = new ImageIcon(resizedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            
            rowData[4] = ii;
            rowData[5]=list.get(i).getID();
            model.addRow(rowData);
            Biriyanitable.setRowHeight(170);
            Biriyanitable.getColumnModel().getColumn(5).setPreferredWidth(170);
            
        }
        

    }//GEN-LAST:event_BtnBiriyaniActionPerformed
      FoodDetailsPage m=new FoodDetailsPage();
   
    private void BtnKababMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKababMouseClicked
        // TODO add your handling code here:
        
        cardParentPanel1.removeAll();
        cardParentPanel1.add(KababPane);
        cardParentPanel1.repaint();
        cardParentPanel1.revalidate();
        
        
      
    }//GEN-LAST:event_BtnKababMouseClicked

    private void BtnKababMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKababMouseEntered
        // TODO add your handling code here:
        BtnKabab.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_BtnKababMouseEntered

    private void BtnKababMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKababMouseExited
        // TODO add your handling code here:
        BtnKabab.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnKababMouseExited

    private void BtnKababMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKababMousePressed
        // TODO add your handling code here:
        BtnKabab.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnKababMousePressed

    private void BtnKababMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKababMouseReleased
        // TODO add your handling code here:
        BtnKabab.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnKababMouseReleased

    private void BtnKababActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKababActionPerformed
        // TODO add your handling code here:
        ArrayList<Kabab_List> list = null;
         try {
             list = KababDB.TableGenerator();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(userViewPage.class.getName()).log(Level.SEVERE, null, ex);
         }
        Object rowData[] = new Object[6];
        
        DefaultTableModel model =  (DefaultTableModel) KababTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        KababTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        KababTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        KababTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        KababTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        KababTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        KababTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
      

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getFood_Item();
            rowData[1] = list.get(i).getRestaurant_Name();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getAvg_rating();
            String temp = list.get(i).getPhoto();
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/Kabab/"+temp));
            Image resizedImage = ii.getImage();
            ii = new ImageIcon(resizedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            
            rowData[4] = ii;
            rowData[5]=list.get(i).getID();
            model.addRow(rowData);
            KababTable.setRowHeight(170);
            KababTable.getColumnModel().getColumn(5).setPreferredWidth(170);
        }
        
    }//GEN-LAST:event_BtnKababActionPerformed

    private void BtnChineseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnChineseMouseClicked
        // TODO add your handling code here:
        cardParentPanel1.removeAll();
        cardParentPanel1.add(ChineseFoodPane);
        cardParentPanel1.repaint();
        cardParentPanel1.revalidate();
     
    }//GEN-LAST:event_BtnChineseMouseClicked

    private void BtnChineseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnChineseMouseEntered
        // TODO add your handling code here:
        BtnChinese.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_BtnChineseMouseEntered

    private void BtnChineseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnChineseMouseExited
        // TODO add your handling code here:
        BtnChinese.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnChineseMouseExited

    private void BtnChineseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnChineseMousePressed
        // TODO add your handling code here:
        BtnChinese.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnChineseMousePressed

    private void BtnChineseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnChineseMouseReleased
        // TODO add your handling code here:
        BtnChinese.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnChineseMouseReleased

    private void BtnChineseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChineseActionPerformed
        // TODO add your handling code here:
         ArrayList<Chinese_List> list = null;
         try {
             list = ChineseDB.TableGenerator();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(userViewPage.class.getName()).log(Level.SEVERE, null, ex);
         }
        Object rowData[] = new Object[6];
        
        DefaultTableModel model =  (DefaultTableModel) ChineseTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        ChineseTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
       ChineseTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        ChineseTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        ChineseTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        ChineseTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        ChineseTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getFood_Item();
            rowData[1] = list.get(i).getRestaurant_Name();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getAvg_rating();
            String temp = list.get(i).getPhoto();
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/Chinese/"+temp));
            Image resizedImage = ii.getImage();
            ii = new ImageIcon(resizedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            
            rowData[4] = ii;
            rowData[5]=list.get(i).getID();
            model.addRow(rowData);
            ChineseTable.setRowHeight(170);
            ChineseTable.getColumnModel().getColumn(5).setPreferredWidth(170);
        }
        

    }//GEN-LAST:event_BtnChineseActionPerformed

    private void BtnItalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnItalianMouseClicked
        // TODO add your handling code here:
        cardParentPanel1.removeAll();
        cardParentPanel1.add(ItalianPane);
        cardParentPanel1.repaint();
        cardParentPanel1.revalidate();

    }//GEN-LAST:event_BtnItalianMouseClicked

    private void BtnItalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnItalianMouseEntered
        // TODO add your handling code here:
        BtnItalian.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_BtnItalianMouseEntered

    private void BtnItalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnItalianMouseExited
        // TODO add your handling code here:
        BtnItalian.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnItalianMouseExited

    private void BtnItalianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnItalianMousePressed
        // TODO add your handling code here:
        BtnItalian.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnItalianMousePressed

    private void BtnItalianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnItalianMouseReleased
        // TODO add your handling code here:
        BtnItalian.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnItalianMouseReleased

    private void BtnItalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnItalianActionPerformed
        // TODO add your handling code here:
        ArrayList<Italian_List> list = null;
         try {
             list = ItalianDB.TableGenerator();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(userViewPage.class.getName()).log(Level.SEVERE, null, ex);
         }
        Object rowData[] = new Object[6];
        
        DefaultTableModel model =  (DefaultTableModel) ItalianTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        ItalianTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        ItalianTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        ItalianTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        ItalianTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        ItalianTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        ItalianTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getFood_Item();
            rowData[1] = list.get(i).getRestaurant_Name();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getAvg_rating();
            String temp = list.get(i).getPhoto();
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/Italian/"+temp));
            Image resizedImage = ii.getImage();
            ii = new ImageIcon(resizedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            
            rowData[4] = ii;
            rowData[5]=list.get(i).getID();
            model.addRow(rowData);
            ItalianTable.setRowHeight(170);
            ItalianTable.getColumnModel().getColumn(5).setPreferredWidth(170);
        }
        
        
    }//GEN-LAST:event_BtnItalianActionPerformed
   ItalianDetails it =new ItalianDetails(); 
    private void ItalianTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalianTableMouseClicked
        // TODO add your handling code here:
        it.setVisible(true);
               it.pack();
               int selectedRow =ItalianTable.getSelectedRow();
        TableModel tm = ItalianTable.getModel();
        String cheese = null,Taste = null;
        String Fname = tm.getValueAt(selectedRow, 0).toString();
        String Rname = tm.getValueAt(selectedRow, 1).toString();
        String price = tm.getValueAt(selectedRow, 2).toString();
        String ar = tm.getValueAt(selectedRow, 3).toString();
        ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 4);
        String ID = tm.getValueAt(selectedRow, 5).toString();
        it.ID.setText(ID);
        it.Fname.setText(Fname);
        it.Rname.setText(Rname);
        it.price.setText(price);
        it.ar.setText(ar);
        it.productPhoto.setIcon(img);
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Cheese_Level,Taste_rating FROM Italian_Foods WHERE Food_ID='"+ID+"'");
            if (rs.next()) 
            {
               
               cheese=rs.getString("Cheese_Level");
               
               Taste=rs.getString("Taste_rating");
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        it.cheese.setText(cheese);
        
        it.taste.setText(Taste);
       
    }//GEN-LAST:event_ItalianTableMouseClicked

    private void BtnIndianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIndianMouseClicked
        // TODO add your handling code here:
        cardParentPanel1.removeAll();
        cardParentPanel1.add(IndianPane);
        cardParentPanel1.repaint();
        cardParentPanel1.revalidate();
    }//GEN-LAST:event_BtnIndianMouseClicked

    private void BtnIndianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIndianMouseEntered
        // TODO add your handling code here:
        BtnIndian.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_BtnIndianMouseEntered

    private void BtnIndianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIndianMouseExited
        // TODO add your handling code here:
        BtnIndian.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnIndianMouseExited

    private void BtnIndianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIndianMousePressed
        // TODO add your handling code here:
        BtnIndian.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnIndianMousePressed

    private void BtnIndianMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIndianMouseReleased
        // TODO add your handling code here:
        BtnIndian.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnIndianMouseReleased

    private void BtnIndianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIndianActionPerformed
        // TODO add your handling code here:
        ArrayList<Indian_List> list = null;
         try {
             list = IndianDB.TableGenerator();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(userViewPage.class.getName()).log(Level.SEVERE, null, ex);
         }
        Object rowData[] = new Object[6];
        
        DefaultTableModel model =  (DefaultTableModel) IndianTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        IndianTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
       IndianTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        IndianTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        IndianTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        IndianTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        IndianTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getFood_Item();
            rowData[1] = list.get(i).getRestaurant_Name();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getAvg_rating();
            String temp = list.get(i).getPhoto();
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/Indian/"+temp));
            Image resizedImage = ii.getImage();
            ii = new ImageIcon(resizedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            
            rowData[4] = ii;
            rowData[5]=list.get(i).getID();
            model.addRow(rowData);
            IndianTable.setRowHeight(170);
            IndianTable.getColumnModel().getColumn(5).setPreferredWidth(170);
        }
    }//GEN-LAST:event_BtnIndianActionPerformed

    private void BtnMexicanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMexicanMouseClicked
        // TODO add your handling code here:
        cardParentPanel1.removeAll();
        cardParentPanel1.add(MexicanPane);
        cardParentPanel1.repaint();
        cardParentPanel1.revalidate();
    }//GEN-LAST:event_BtnMexicanMouseClicked

    private void BtnMexicanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMexicanMouseEntered
        // TODO add your handling code here:
        BtnMexican.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_BtnMexicanMouseEntered

    private void BtnMexicanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMexicanMouseExited
        // TODO add your handling code here:
        BtnMexican.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnMexicanMouseExited

    private void BtnMexicanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMexicanMousePressed
        // TODO add your handling code here:
        BtnMexican.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_BtnMexicanMousePressed

    private void BtnMexicanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMexicanMouseReleased
        // TODO add your handling code here:
        BtnMexican.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_BtnMexicanMouseReleased

    private void BtnMexicanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMexicanActionPerformed
        // TODO add your handling code here:
        ArrayList<Mexican_List> list = null;
         try {
             list = MexicanDB.TableGenerator();
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(userViewPage.class.getName()).log(Level.SEVERE, null, ex);
         }
        Object rowData[] = new Object[6];
        
        DefaultTableModel model =  (DefaultTableModel) MexicanTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        MexicanTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
       MexicanTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        MexicanTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        MexicanTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        MexicanTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
        MexicanTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getFood_Item();
            rowData[1] = list.get(i).getRestaurant_Name();
            rowData[2] = list.get(i).getPrice();
            rowData[3] = list.get(i).getAvg_rating();
            String temp = list.get(i).getPhoto();
            ImageIcon ii = new ImageIcon(getClass().getResource("/images/Mexican/"+temp));
            Image resizedImage = ii.getImage();
            ii = new ImageIcon(resizedImage.getScaledInstance(150, 150, Image.SCALE_SMOOTH));
            
            rowData[4] = ii;
            rowData[5]=list.get(i).getID();
            model.addRow(rowData);
            MexicanTable.setRowHeight(170);
            MexicanTable.getColumnModel().getColumn(5).setPreferredWidth(170);
        }
    }//GEN-LAST:event_BtnMexicanActionPerformed

    private void accountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_accountButtonMouseClicked

    private void accountButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseEntered
        // TODO add your handling code here:
        accountButton.setBackground(new Color(0, 137, 123));
    }//GEN-LAST:event_accountButtonMouseEntered

    private void accountButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseExited
        // TODO add your handling code here:
        accountButton.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_accountButtonMouseExited

    private void accountButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMousePressed
        // TODO add your handling code here:
        accountButton.setBackground(new Color(0, 77, 64));
    }//GEN-LAST:event_accountButtonMousePressed

    private void accountButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountButtonMouseReleased
        // TODO add your handling code here:
        accountButton.setBackground(new Color(0, 150, 136));
    }//GEN-LAST:event_accountButtonMouseReleased

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_accountButtonActionPerformed

    private void BiriyanitableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BiriyanitableMouseClicked
        // TODO add your handling code here:
        m.setVisible(true);
               m.pack();
               int selectedRow = Biriyanitable.getSelectedRow();
        TableModel tm = Biriyanitable.getModel();
        String oil = null,spice = null,masala = null,Taste = null;
        String Fname = tm.getValueAt(selectedRow, 0).toString();
        String Rname = tm.getValueAt(selectedRow, 1).toString();
        String price = tm.getValueAt(selectedRow, 2).toString();
        String ar = tm.getValueAt(selectedRow, 3).toString();
        ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 4);
        String ID = tm.getValueAt(selectedRow, 5).toString();
        m.ID.setText(ID);
        m.Fname.setText(Fname);
        m.Rname.setText(Rname);
        m.price.setText(price);
        m.ar.setText(ar);
        m.productPhoto.setIcon(img);
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Oil_level,Spice_Level,Masala_rating,Taste_rating FROM Biriyani_Items WHERE Food_ID='"+ID+"'");
            if (rs.next()) 
            {
               oil=rs.getString("Oil_level");
               spice=rs.getString("Spice_Level");
               masala=rs.getString("Masala_rating");
               Taste=rs.getString("Taste_rating");
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        m.oil.setText(oil);
        m.spice.setText(spice);
        m.masala.setText(masala);
        m.taste.setText(Taste);
        
    }//GEN-LAST:event_BiriyanitableMouseClicked
 KababDetails k= new KababDetails();
    private void KababTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KababTableMouseClicked
        // TODO add your handling code here:
        k.setVisible(true);
               k.pack();
               int selectedRow = KababTable.getSelectedRow();
        TableModel tm = KababTable.getModel();
        String oil = null,sauce = null,masala = null,Taste = null;
        String Fname = tm.getValueAt(selectedRow, 0).toString();
        String Rname = tm.getValueAt(selectedRow, 1).toString();
        String price = tm.getValueAt(selectedRow, 2).toString();
        String ar = tm.getValueAt(selectedRow, 3).toString();
        ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 4);
        String ID = tm.getValueAt(selectedRow, 5).toString();
        k.ID.setText(ID);
        k.Fname.setText(Fname);
        k.Rname.setText(Rname);
        k.price.setText(price);
        k.ar.setText(ar);
        k.productPhoto.setIcon(img);
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Oil_level,Masala_rating,Sauces_rating,Taste_rating FROM Kabab_Items WHERE Food_ID='"+ID+"'");
            if (rs.next()) 
            {
               oil=rs.getString("Oil_level");
               sauce=rs.getString("Sauces_rating");
               masala=rs.getString("Masala_rating");
               Taste=rs.getString("Taste_rating");
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        k.oil.setText(oil);
        k.sauce.setText(sauce);
        k.masala.setText(masala);
        k.taste.setText(Taste);
        
    }//GEN-LAST:event_KababTableMouseClicked
    ChineseDetails c= new ChineseDetails();
    private void ChineseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChineseTableMouseClicked
        // TODO add your handling code here:
        c.setVisible(true);
               c.pack();
               int selectedRow =ChineseTable.getSelectedRow();
        TableModel tm = ChineseTable.getModel();
        String spice = null,sauce = null,Taste = null;
        String Fname = tm.getValueAt(selectedRow, 0).toString();
        String Rname = tm.getValueAt(selectedRow, 1).toString();
        String price = tm.getValueAt(selectedRow, 2).toString();
        String ar = tm.getValueAt(selectedRow, 3).toString();
        ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 4);
        String ID = tm.getValueAt(selectedRow, 5).toString();
        c.ID.setText(ID);
        c.Fname.setText(Fname);
        c.Rname.setText(Rname);
        c.price.setText(price);
        c.ar.setText(ar);
        c.productPhoto.setIcon(img);
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Spice_Level,Sauce_rating,Taste_rating FROM Chinese_Foods WHERE Food_ID='"+ID+"'");
            if (rs.next()) 
            {
               
               sauce=rs.getString("Sauce_rating");
               spice=rs.getString("Spice_Level");
               Taste=rs.getString("Taste_rating");
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        c.sauce.setText(sauce);
        c.spice.setText(spice);
        c.taste.setText(Taste);
    }//GEN-LAST:event_ChineseTableMouseClicked
   IndianDetails in=new IndianDetails ();
    private void IndianTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IndianTableMouseClicked
        // TODO add your handling code here:
        in.setVisible(true);
               in.pack();
               int selectedRow = IndianTable.getSelectedRow();
        TableModel tm = IndianTable.getModel();
        String spice = null,masala = null,Taste = null;
        String Fname = tm.getValueAt(selectedRow, 0).toString();
        String Rname = tm.getValueAt(selectedRow, 1).toString();
        String price = tm.getValueAt(selectedRow, 2).toString();
        String ar = tm.getValueAt(selectedRow, 3).toString();
        ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 4);
        String ID = tm.getValueAt(selectedRow, 5).toString();
        in.ID.setText(ID);
        in.Fname.setText(Fname);
        in.Rname.setText(Rname);
        in.price.setText(price);
        in.ar.setText(ar);
        in.productPhoto.setIcon(img);
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Spice_Level,Masala_rating,Taste_rating FROM Indian_Foods WHERE Food_ID='"+ID+"'");
            if (rs.next()) 
            {
               
               spice=rs.getString("Spice_Level");
               masala=rs.getString("Masala_rating");
               Taste=rs.getString("Taste_rating");
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        in.spice.setText(spice);
        in.masala.setText(masala);
        in.taste.setText(Taste);
    }//GEN-LAST:event_IndianTableMouseClicked
    MexicanDetails me=new MexicanDetails();
    private void MexicanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexicanTableMouseClicked
        // TODO add your handling code here:
        me.setVisible(true);
               me.pack();
               int selectedRow =MexicanTable.getSelectedRow();
        TableModel tm = MexicanTable.getModel();
        String meyonese = null,Taste = null;
        String Fname = tm.getValueAt(selectedRow, 0).toString();
        String Rname = tm.getValueAt(selectedRow, 1).toString();
        String price = tm.getValueAt(selectedRow, 2).toString();
        String ar = tm.getValueAt(selectedRow, 3).toString();
        ImageIcon img = (ImageIcon) tm.getValueAt(selectedRow, 4);
        String ID = tm.getValueAt(selectedRow, 5).toString();
        me.ID.setText(ID);
        me.Fname.setText(Fname);
        me.Rname.setText(Rname);
        me.price.setText(price);
        me.ar.setText(ar);
        me.productPhoto.setIcon(img);
        try
        {Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
          Connection   con = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=ProjectfoodHUB;selectMethod=cursor", "sa", "123456");
            
            Statement ps = con.createStatement();
            ResultSet rs;
            rs = ps.executeQuery("SELECT Meyonese_rating,Taste_rating FROM Mexican_Foods WHERE Food_ID='"+ID+"'");
            if (rs.next()) 
            {
               
               meyonese=rs.getString("Meyonese_rating");
               
               Taste=rs.getString("Taste_rating");
            }
            
        }
        
         catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AddItemsPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        me.meyonese.setText(meyonese);
        
        me.taste.setText(Taste);
    }//GEN-LAST:event_MexicanTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userViewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userViewPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel BiriyaniPane;
    private javax.swing.JTable Biriyanitable;
    private javax.swing.JButton BtnBiriyani;
    private javax.swing.JButton BtnChinese;
    private javax.swing.JButton BtnIndian;
    private javax.swing.JButton BtnItalian;
    private javax.swing.JButton BtnKabab;
    private javax.swing.JButton BtnMexican;
    private javax.swing.JPanel ChineseFoodPane;
    private javax.swing.JTable ChineseTable;
    private javax.swing.JPanel IndianPane;
    private javax.swing.JTable IndianTable;
    private javax.swing.JPanel ItalianPane;
    private javax.swing.JTable ItalianTable;
    private javax.swing.JPanel KababPane;
    private javax.swing.JTable KababTable;
    private javax.swing.JPanel MexicanPane;
    private javax.swing.JTable MexicanTable;
    private javax.swing.JTable SearchTable;
    private javax.swing.JButton accountButton;
    private javax.swing.JPanel cardParentPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel1;
    // End of variables declaration//GEN-END:variables
}
